name: CI/CD for Churn Prediction

on:
  push:
    branches:
      - main

env: 
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

jobs:
  data_load:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r ./scripts/analysis/requirements.txt
      - name: Run data load script
        run: python scripts/data/data_load.py

  dbt_build:
    runs-on: ubuntu-latest
    needs: data_load
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dbt dependencies
        run: pip install dbt-snowflake
      - name: Run dbt deps
        run: dbt deps
      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "sales_app:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: '${{ secrets.SNOWFLAKE_ACCOUNT }}'" >> ~/.dbt/profiles.yml
          echo "      user: '${{ secrets.SNOWFLAKE_USER }}'" >> ~/.dbt/profiles.yml
          echo "      password: '${{ secrets.SNOWFLAKE_PASSWORD }}'" >> ~/.dbt/profiles.yml
          echo "      role: '${{ secrets.SNOWFLAKE_ROLE }}'" >> ~/.dbt/profiles.yml
          echo "      warehouse: '${{ secrets.SNOWFLAKE_WAREHOUSE }}'" >> ~/.dbt/profiles.yml
          echo "      database: '${{ secrets.SNOWFLAKE_DATABASE }}'" >> ~/.dbt/profiles.yml
          echo "      schema: '${{ secrets.SNOWFLAKE_SCHEMA }}'" >> ~/.dbt/profiles.yml
      - name: Run dbt build
        run: dbt build

  feedback_analysis:
    runs-on: ubuntu-latest
    needs: dbt_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install notebook dependencies
        run: pip install -r ./scripts/analysis/requirements.txt
      - name: Run Snowflake notebook script
        run: python scripts/analysis/feedback_analysis.py
      - name: Send Teams Notifications
        run: python ./scripts/analysis/notifications.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_URL_TRAINING: ${{ secrets.WEBHOOK_URL_TRAINING }}
