name: CI/CD for Churn Prediction

on:
  push:
    branches:
      - main

jobs:
  data_load:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🗂️
        uses: actions/checkout@v2
        
      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Check directory structure
        run: |
          echo "📂 Checking directory structure..."
          ls -R
          echo "✅ Directory structure checked."

      - name: Install dependencies
        run: |
          echo "🔧 Installing dependencies..."
          pip install -r ./scripts/analysis/requirements.txt
          echo "✅ Dependencies installed."

      - name: Run data load script
        run: |
          echo "📊 Running data load script..."
          python scripts/data/data_load.py 
          echo "✅ Data load script executed successfully."
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

  dbt_build:
    runs-on: ubuntu-latest
    needs: data_load
    steps:
      - name: Checkout code 📂
        uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dbt dependencies 📦
        run: |
          echo "🔧 Installing dbt dependencies..."
          pip install dbt-snowflake
          echo "✅ dbt dependencies installed."

      - name: Install dbt dependencies with dbt deps 🛠️
        run: |
          echo "🔧 Running dbt deps..."
          dbt deps
          echo "✅ dbt deps completed."

      - name: Create dbt profiles.yml 📝
        run: |
          echo "📝 Creating dbt profiles.yml..."
          mkdir -p ~/.dbt
          echo "sales_app:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: '${{ secrets.SNOWFLAKE_ACCOUNT }}'" >> ~/.dbt/profiles.yml
          echo "      user: '${{ secrets.SNOWFLAKE_USER }}'" >> ~/.dbt/profiles.yml
          echo "      password: '${{ secrets.SNOWFLAKE_PASSWORD }}'" >> ~/.dbt/profiles.yml
          echo "      role: '${{ secrets.SNOWFLAKE_ROLE }}'" >> ~/.dbt/profiles.yml
          echo "      warehouse: '${{ secrets.SNOWFLAKE_WAREHOUSE }}'" >> ~/.dbt/profiles.yml
          echo "      database: '${{ secrets.SNOWFLAKE_DATABASE }}'" >> ~/.dbt/profiles.yml
          echo "      schema: '${{ secrets.SNOWFLAKE_SCHEMA }}'" >> ~/.dbt/profiles.yml
          echo "✅ dbt profiles.yml created."

      - name: Run dbt build 🚀
        run: |
          echo "🚀 Running dbt build..."
          dbt build
          echo "✅ dbt build completed."

  feedback_analysis:
    runs-on: ubuntu-latest
    needs: dbt_build
    steps:
      - name: Checkout code 📂
        uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies for notebook
        run: |
          echo "🔧 Installing notebook dependencies..."
          pip install -r ./scripts/analysis/requirements.txt
          echo "✅ Notebook dependencies installed."

      - name: Run Snowflake notebook script 🎯
        run: |
          echo "🎯 Running Snowflake notebook script..."
          python scripts/analysis/feedback_analysis.py
          echo "✅ Snowflake notebook script executed."

        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

      - name: Send teams Notifications 📧
        run: |
          echo "📢 Sending email notifications..."
          python ./scripts/analysis/notifications.py 
          echo "🎉 Email notifications sent successfully."
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_URL_TRAINING: ${{ secrets.WEBHOOK_URL_TRAINING }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
